/**
 * Implementation of arbitrary length LFSR.
 * Input: binary sequence describing the LFSR.
 * Output: binary sequence generated by the LFSR in one period.
 */

#include "lfsr.h"

/**
 * Circularly shift the given char array (strictly null-terminated) right.
 */
void circular_shift_right(char arr[]) {
	int i = 0;
	int l = strlen(arr);
	char last = arr[l - 1];
	for (i = l - 1; i >= 1; i--) {
		arr[i] = arr[i - 1];
	}
	arr[i] = last;
}

/**
 * Run the given LFSR howmany times and store the result as a
 * string into the given char array.
 */
void get_lfsr_output(LFSR *lfsr_in, char *lfsr_output, int howmany) {
	char *lfsr_descriptor = lfsr_in->descriptor,
		*lfsr_state = lfsr_in->initial_state;
	unsigned int j;
	int i = 0,
		is_first_digit,
		cur_desc_digit, 
		cur_state_digit,
		period = (howmany > 0)? howmany : DSIZE,
		best_period = pow(2, strlen(lfsr_descriptor)) - 1,
		new_digit;
	char output_digit_char,
		new_digit_char;

	printf("Best expected period: %d\n", best_period);
	j = 0;
	while (j < period) {
		for (i = 0, is_first_digit = 1; i < strlen(lfsr_descriptor); i++) {
			cur_desc_digit = (lfsr_descriptor[i] == '0')? 0 : 1;
			// printf("Pos %d is %d\n", i, cur_desc_digit);
			if (cur_desc_digit == 1) {
				cur_state_digit = (lfsr_state[i] == '0')? 0 : 1;
				if (is_first_digit) {
					new_digit = cur_state_digit;
					is_first_digit = 0;
					// printf("First digit! Result is %d, value is %d\n", result_digit, cur_state_digit);	
				} else {
					new_digit ^= cur_state_digit;					
					// printf("...Value is %d, result is %d\n", cur_state_digit, result_digit);	
				}
			}
			// printf("Processing (%s) (%d) %d\n", lfsr_state, i, cur_state_digit);
		}
		new_digit_char = (new_digit == 0)? '0' : '1';
		output_digit_char = lfsr_state[i - 1]; // i = len(state)
		circular_shift_right(lfsr_state);
		lfsr_state[0] = new_digit_char;
		// printf("State after execution %s\n", lfsr_state);
		lfsr_output[j] = output_digit_char;
		// printf("Current digit: %c\n", output_digit_char);
		j++;
	}
	// Pick the last value and shift the register right
	lfsr_output[j] = '\0';
}